= NetworkPolicy: A Commodore component to manage NetworkPolicy

{doctitle} provides the tooling to manage a set of NetworkPolicies in all the namespaces on a cluster.
The intention is to create a safe default.
This is done by isolating the network of a namespace.
The created policies will allow only traffic from pods within the same network.
They will also allow traffic from selected namespaces.
The latter is needed for ingress and monitoring to work.

This component assumes that a cluster was set up with a https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins[network plugin] that supports NetworkPolicies.

An Espejote ManagedResource is used to create the policies.
The ManagedResource is configured to ignore namespaces having the label `network-policies.syn.tools/no-defaults` (the value doesn't matter).
Namespaces can also be ignored by listing them in the `ignoredNamespaces` parameter.

[IMPORTANT]
====
The content of the created NetworkPolicies is enforced.
Changes from other sources will be overwritten.
If changes to the default policies are required, add the ignore label and create them on your own.

If you'd rather customize the policies applied by this component, see the xref:how-tos/using-customizing-policies.adoc[].
====

See also the xref:references/parameters.adoc[parameters reference].
