= Parameters

The parent key for all of the following parameters is `networkpolicy`.

== `labels`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
noDefaults: network-policies.syn.tools/no-defaults
purgeDefaults: network-policies.syn.tools/purge-defaults
----

Name of the labels to be used in other components.

== `allowFromSameNamespace.podSelector`

[horizontal]
type:: dictionary
default:: {}

A comprehensive list of values that the podSelector object supports.
For more information on the podSelector object, refer to the kubectl explain networkpolicy.spec.podSelector command.

[source,yaml]
----
allowFromSameNamespace:
  podSelector:
    matchLabels:
      io.cilium.k8s.policy.cluster: cluster1
----

In the given example, traffic will be permitted on a Cilium Cluster Mesh-enabled cluster only within the same local cluster network.
By default, the {} selector allows traffic between pods of all Cilium Cluster Mesh-enabled clusters that share the same namespace name.

== `allowNamespaceLabels`

[horizontal]
type:: list of tuples
default:: empty list

A list of labels matching namespaces to allow traffic from.
Each list item can contain several key value pairs.
They result in an `AND` condition.
Individual list items will result in an `OR` condition.

[source,yaml]
----
allowNamespaceLabels:
  - my-label-a: true
    my-label-b: true
  - my-label-c: true
----

In the above example, traffic will be allowed if a namespaces has the label `my-label-a=true` AND `my-label-b=true`.
Traffic will also be allowed if a namespace is labeled `my-label-c`.

== `ignoredNamespaces`

[horizontal]
type:: list of strings
default:: empty list

A list of namespace names where no default NetworkPolicies will be created.
Default NetworkPolicies will be purged for all namespaces in this list.

== `networkPlugin`

[horizontal]
type:: string
default:: `''`

The network plugin installed on the cluster.

[CAUTION]
====
This needs to be set when using the Cilium network plugin.
Otherwise some policies might not be applied correctly.
====

== Example

[source,yaml]
----
# Allow traffic from ingress and monitoring
allowNamespaceLabels:
  - network.openshift.io/policy-group: monitoring
  - network.openshift.io/policy-group: ingress
# Do not create the default policies in the OpenShift namespaces.
ignoredNamespaces:
  - openshift
  - openshift-apiserver
  - openshift-apiserver-operator
  - …
----
